### ISSUE TITLE
PLCrashReporter crashes when handling a crash

### ISSUE THREAD

**Issue by adammarks** [backtrace-labs/plcrashreporter#8]
**Problem:**

When we use the following code to generate a crash, your fork of PLCrashReporter ends up crashing while handling this crash,  therefore the stack doesn't indicate the actual crash.

```
-(NSString *) concatString:(NSString*) s1 toString:(NSString *) s2
{
   return [s1 stringByAppendingString:s2];
}

- (BOOL) validateMenuItem:(NSMenuItem *)item
{
   BOOL result = NO;
   NSLog(@"%@", [self concatString:@"bob" toString:nil]);
```

**Expected:**

A crash report that has validateMenuItem: in it.

**Actual:**

The crash report that shows PLCrashReporter itself as the item that is crashing.  

```
[ 00 ] __pthread_kill
[ 01 ] abort
[ 02 ] -[PLCrashReporter setCrashCallbacks:].cold.1
[ 03 ] -[PLCrashReporter generateLiveReportWithThread:]
[ 04 ] DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*)
[ 05 ] SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*)
[ 06 ] SendEventToEventTarget
[ 07 ] SendHICommandEvent(unsigned int, HICommand const*, unsigned int, unsigned int, unsigned char, void const*, OpaqueEventTargetRef*, OpaqueEventTargetRef*, OpaqueEventRef**)
[ 08 ] UpdateHICommandStatusWithCachedEvent
[ 09 ] HIApplication::EventHandler(OpaqueEventHandlerCallRef*, OpaqueEventRef*, void*)
[ 10 ] DispatchEventToHandlers(EventTargetRec*, OpaqueEventRef*, HandlerCallRec*)
[ 11 ] SendEventToEventTargetInternal(OpaqueEventRef*, OpaqueEventTargetRef*, HandlerCallRec*)
[ 12 ] SendEventToEventTarget
[ 13 ] SendMenuOpening(MenuSelectData*, MenuData*, double, unsigned int, unsigned int, __CFDictionary*, unsigned char, unsigned char*)
[ 14 ] PopUpMenuSelectCore(MenuData*, Point, double, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, unsigned int, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*)
[ 15 ] _HandlePopUpMenuSelection8(OpaqueMenuRef*, OpaqueEventRef*, unsigned int, Point, unsigned short, unsigned int, unsigned int, Rect const*, unsigned short, Rect const*, Rect const*, __CFDictionary const*, __CFString const*, OpaqueMenuRef**, unsigned short*)
[ 16 ] _HandlePopUpMenuSelectionWithDictionary
[ 17 ] _NSSLMPopUpCarbonMenu3
[ 18 ] -[NSCarbonMenuImpl _popUpContextMenu:withEvent:forView:withFont:]
[ 19 ] -[NSMenu _popUpContextMenu:withEvent:forView:withFont:]
[ 20 ] -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:]
[ 21 ] -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:]
[ 22 ] -[NSWindow(NSEventRouting) sendEvent:]
[ 23 ] -[TitleBarMoveFinishNotifyWindow sendEvent:]
...
[ 28 ] -[NSApplication run]
[ 29 ] NSApplicationMain
[ 30 ] start
```

**Comment by krml19** [comment]
Hi @adammarks, thanks for reporting this issue. 

I created a sample application to reproduce the error that you are getting. However, I am unable to do so. The stack trace that I got looks fine. You can find the sample application on the [feature branch](https://github.com/backtrace-labs/plcrashreporter/tree/fix/issue-8-crashreporter-crashes-when-handling-a-crash).

Can you please provide a sample application or modify the existing one in order to reproduce the reported issue?

**Crash stack trace:**
```
2020-07-18 17:25:21.952540+0200 CrashReporter-macOS-ObjC-Example[45286:494486] [General] *** -[__NSCFConstantString stringByAppendingString:]: nil argument
2020-07-18 17:25:21.954554+0200 CrashReporter-macOS-ObjC-Example[45286:494486] [General] (
	0   CoreFoundation                      0x00007fff38978b57 __exceptionPreprocess + 250
	1   libobjc.A.dylib                     0x00007fff717bf5bf objc_exception_throw + 48
	2   Foundation                          0x00007fff3af42e53 -[NSString stringByAppendingString:] + 238
	3   CrashReporter-macOS-ObjC-Example    0x0000000100001043 -[ViewController concatString:toString:] + 99
	4   CrashReporter-macOS-ObjC-Example    0x000000010000124b -[ViewController validateMenuItem:] + 75
	5   CrashReporter-macOS-ObjC-Example    0x00000001000011d3 -[ViewController onButtonTapped:] + 227
	6   AppKit                              0x00007fff35daf7a7 -[NSApplication(NSResponder) sendAction:to:from:] + 299
	7   AppKit                              0x00007fff35daf642 -[NSControl sendAction:to:] + 86
	8   AppKit                              0x00007fff35daf574 __26-[NSCell _sendActionFrom:]_block_invoke + 136
	9   AppKit                              0x00007fff35daf476 -[NSCell _sendActionFrom:] + 171
	10  AppKit                              0x00007fff35daf3bd -[NSButtonCell _sendActionFrom:] + 96
	11  AppKit                              0x00007fff35dab69b NSControlTrackMouse + 1745
	12  AppKit                              0x00007fff35daafa2 -[NSCell trackMouse:inRect:ofView:untilMouseUp:] + 130
	13  AppKit                              0x00007fff35daae61 -[NSButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 691
	14  AppKit                              0x00007fff35daa1dd -[NSControl mouseDown:] + 748
	15  AppKit                              0x00007fff35da85f0 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 4914
	16  AppKit                              0x00007fff35d12e21 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2612
	17  AppKit                              0x00007fff35d121c9 -[NSWindow(NSEventRouting) sendEvent:] + 349
	18  AppKit                              0x00007fff35d10554 -[NSApplication(NSEvent) sendEvent:] + 352
	19  AppKit                              0x00007fff35b5d5bf -[NSApplication run] + 707
	20  AppKit                              0x00007fff35b2f396 NSApplicationMain + 777
	21  CrashReporter-macOS-ObjC-Example    0x00000001000012cf main + 47
	22  libdyld.dylib                       0x00007fff72967cc9 start + 1
)
```

**Environment:** 
- MacBook Pro running on macOS Catalina (10.15.6)
- Xcode 11.6

**Comment by adammarks** [comment]
@krml19  In the sample you are calling validateMenuItem  directly.  To see the crash,  change your code to get the OS to call it for you.

Create a menu and the target of that menu needs to implement validateMenuItem and then invoke it by opening the menu.

For more info : https://developer.apple.com/documentation/objectivec/nsobject/1518160-validatemenuitem

**Comment by krml19** [comment]
@adammarks Thanks for the hints. I've updated the sample application appropriately and now I'm able to re-create this issue. Will keep you updated on the progress.

**Comment by krml19** [comment]
@adammarks The application throws an unhandled exception when the system calls the method `validateMenuItem`, and it fails. Such exceptions can be caught by the [top-level error handler]( https://developer.apple.com/documentation/foundation/1409609-nssetuncaughtexceptionhandler). In the default configuration of `PLCrashReporter`, the uncaught exception handler catches such exceptions, writes the original exception, and calls abort function to terminate the program abnormally. The related code can be found [here](https://github.com/backtrace-labs/plcrashreporter/blob/backtrace/Sources/PLCrashReporter.m#L373). Therefore, the stack trace will always contain calls to `PLCrashReporter`’s methods proceeded by `abort` function. That's why I don't think there is a problem, do you still?
Besides, the [Backtrace](https://backtrace.io/) user interface can be configured to de-emphasize or filter out those frames from various views.

**Comment by adammarks** [comment]
@krml19  Ok,  I looked at the sample code and it does throw the exception when viewing a menu now.

Now,  send that crash report up to backtrace and look at it,  It won't have validateMenu in the crash report and that is a problem.

**Comment by sbahra** [comment]
We're looking into this. Specifically, looking into the debug information for the Apple-provided symbol.

**Comment by sbahra** [comment]
@adammarks We are in the process of rolling out a major improvement. You'll note system symbols get resolved now, some incoming changes will improve rendering of exceptions. I'll be moving this to ZenDesk so we can better track it and gather your feedback. I'll ping you on there once the change is deployed to your host.
